---
conversation_task:
  description: >
    Based on the conversation so far and the latest message {user_input},
    determine whether the user is making a new event search or 
    referring to a previous recommendation. If it's a new query, extract relevant filters
    such as genre, performer, date and time, price, popularity, and size of the event.
    If it’s a follow-up (e.g. “tell me more about the Knicks game”),
    identify the referenced event.
  expected_output: >
    If new query, a set of user preferences including genre, performer, date and
    time, price, popularity, and size of the event. If follow-up, event title or identifier for deeper lookup.
  async_execution: false
  agent: conversation_specialist

fetch_events_data_task:
  description: >
    Conduct web searches and extract detailed ticket information based on user preferences.
    Return a comprehensive list of events including event name, date, location, price,
    and ticket link.
  expected_output: >
    A list of comprehensive event results (name, date, location, price, ticket URL).
  async_execution: false
  agent: web_search_expert
  context:
    - conversation_task

filter_and_rank_task:
  description: >
    Validate the reasonability of ticket results and rank the top 5 based on relevance
    to user preferences.
  expected_output: >
    A ranked list of the top 5 events with available tickets, including event name, date,
    location, price, and ticket URL.
  async_execution: false
  agent: filtering_and_ranking_specialist
  context:
    - fetch_events_data_task

present_results_task:
  description: >
    Present the ranked event results to the user in natural language.
    Display as bullet points with event name, date, time, location, price, a link,
    and a short description. Ask the user if they want more info on any.
  expected_output: >
    A natural language summary of the top 5 events with details and follow-up question.
  async_execution: false
  agent: conversation_specialist
  context:
    - filter_and_rank_task

fetch_event_details_task:
  description: >
    Given the user's follow-up {user_input}, the previously shown recommendations, and the user preferences,
    identify the referenced event and provide additional details such as time,
    location, performers, seating, and price range.
  expected_output: >
    A natural language summary with additional information for a selected event.
  async_execution: false
  agent: scraping_specialist
  context:
    - present_results_task
    - conversation_task